<!DOCTYPE html>
<html>
    <head>
        <title>Error</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- <link rel="shortcut icon" href="/assets/img/oms.ico"> -->
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <!-- 新 Bootstrap 核心 CSS 文件 -->
        <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
        <script src="//cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
        <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
        <script src="//cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/screen.css" />
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>
        <div class="container">
            <h1><?php echo $this->error;?></h1>
            <?php echo ($this->message) ? '<pre>'.$this->message.'</pre>' : ''; ?>
            <?php echo ($this->trace) ? '<pre>'.$this->trace.'</pre>' : ''; ?>
        </div>
    </body>
</html>


